### ISSUE TITLE
Request to Add Product in Start React 

### ISSUE THREAD

**Issue by maheshwari-1153** [adityasonel/TheReactApp#1]
Hello,
I am Maheshwari from team [GeekyAnts](https://geekyants.com/). 

On behalf of [Start React](https://startreact.com/), we add open source products which we find helpful to the community & also we provide credits to author itself.

Let me know if you are interested showcase your product in our open source website. 

Looking forward to hear from you.

**Comment by adityasonel** [comment]
Yeah sure,

It is great idea, there is no problem to me in that. Via your platform this project will get the right way where I always wanted that it be.

Thanks @maheshwari-1153,
And sorry for late reply!
